//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEntities3 : DbContext
    {
        public projectEntities3()
            : base("name=projectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<addtocart> addtocarts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<deliverinfo> deliverinfoes { get; set; }
        public DbSet<myorder> myorders { get; set; }
        public DbSet<Orderdetail> Orderdetails { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<returndeteli> returndetelis { get; set; }
        public DbSet<Returnproduct> Returnproducts { get; set; }
        public DbSet<Systemuser> Systemusers { get; set; }
    }
}
