//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returnproduct
    {
        public Returnproduct()
        {
            this.returndetelis = new HashSet<returndeteli>();
        }
    
        public int id { get; set; }
        public string return_id { get; set; }
        public string reason { get; set; }
        public System.DateTime date { get; set; }
        public string statuse { get; set; }
    
        public virtual ICollection<returndeteli> returndetelis { get; set; }
    }
}
